### ISSUE TITLE
Errors for running Benson Retinotopy atlas

### ISSUE THREAD

**Issue by htakemur** [noahbenson/neuropythy#21]
Hello @noahbenson 

I am now getting a following error when I run Benson Retinotopy atlas using neuropathy... Do you have any thought on this error? 

Command: 
python -m neuropythy benson14_retinotopy SUBJID --vol-format=nifti

Traceback (most recent call last):
  File "/home/htakemur/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/htakemur/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/htakemur/anaconda3/lib/python3.7/site-packages/neuropythy/__main__.py", line 19, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/htakemur/anaconda3/lib/python3.7/site-packages/neuropythy/__main__.py", line 16, in main
    return commands[argv[0]](argv[1:])
  File "/home/htakemur/anaconda3/lib/python3.7/site-packages/neuropythy/commands/benson14_retinotopy.py", line 155, in main
    sub = subject(subnm)
  File "/home/htakemur/anaconda3/lib/python3.7/site-packages/neuropythy/freesurfer/core.py", line 738, in subject
    sub = subject_from_filemap(fmap, name=name, check_path=check_path, meta_data=meta_data)
  File "/home/htakemur/anaconda3/lib/python3.7/site-packages/neuropythy/freesurfer/core.py", line 658, in subject_from_filemap
    raise ValueError('given path does not appear to hold a freesurfer subject')
ValueError: given path does not appear to hold a freesurfer subject

**Comment by htakemur** [comment]
I will close it once, since this looks like due to type error of subject's name. I obtained different error, but will open different thread.
