### ISSUE TITLE
Cannot export Benson atlas nifti file by neuropythy

### ISSUE THREAD

**Issue by htakemur** [noahbenson/neuropythy#22]
Hello @noahbenson 

I could run neuropythy benson14_retinotopy rightly, if I did not include " --volume_format=nifti" option. However, when I include this option, I obtained a following error. Therefore, subject's name and pass to freesurfer directory seems to be valid, but by some reasons I could not export atlas into nifti format. If you kindly give me any thoughts, I will greatly appreciate. 

Command:
python -m neuropythy benson14_retinotopy SUBJNAME --volume_format=nifti

Error message: 
/home/htakemur/anaconda3/lib/python3.7/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
Traceback (most recent call last):
  File "/home/htakemur/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/htakemur/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/htakemur/anaconda3/lib/python3.7/site-packages/neuropythy/__main__.py", line 19, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/htakemur/anaconda3/lib/python3.7/site-packages/neuropythy/__main__.py", line 16, in main
    return commands[argv[0]](argv[1:])
  File "/home/htakemur/anaconda3/lib/python3.7/site-packages/neuropythy/commands/benson14_retinotopy.py", line 155, in main
    sub = subject(subnm)
  File "/home/htakemur/anaconda3/lib/python3.7/site-packages/neuropythy/freesurfer/core.py", line 722, in subject
    if pdir is None: raise ValueError('could not find freesurfer subject: %s' % path)
ValueError: could not find freesurfer subject: --volume_format=nifti

**Comment by noahbenson** [comment]
i think the issue is that the argument for benson14_retinotopy is `--vol-format=nifti` rather than `--volume_format=nifti` (note the hyphen instead of underscore).

Also, I might recommend using the `atlas` command; it is just slightly different from the benson14_retinotopy command. It supports other atlases aside from benson14 and I keep it more up-to-date. I think you would want to run it like this:

```
python -m neuropythy atlas SUBJID --verbose --volume-export --volume-format=nifti
```

(`--volume-format` is correct for atlas while `--vol-format` is correct for benson14_retinotopy.)

**Comment by htakemur** [comment]
Thank you very much! It is working now by using "atlas"!
